import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import Footer from '../components/Footer'
import { MicrophoneIcon, SearchIcon, ViewGridIcon } from '@heroicons/react/solid'

export default function Home() {
  return (
    <div className='flex flex-col justify-center h-screen'>
      <Head>
        <title>Search It</title>
        <meta name="description" content="Generated by create next app. Search It, a Google Clone." />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <header className='flex w-full p-5 justify-between bg-blue-400 text-md text-gray-700'>
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

        <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>


        <Avatar url={'https://coaching.papareact.com/a19'}/>
        </div>
      </header>

        
          <form className='flex flex-col items-center mt-44 flex-grow'>
            <Image 
            src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
            height={100}
            width={300}
            
            />
            <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-400 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
              <SearchIcon className='h-5 mr-3 text-gray-500'/>
              <input type='text' className='focus:outline-none flex-grow'/>

              <MicrophoneIcon className='h-5'/>
            </div>
            <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-2 sm:flex-row sm:space-x-4'>
              <button className='btn'>Google Search</button>

              <button className='btn'>I'm Feeling Lucky</button>
            </div>
          </form>

          <Footer />
    </div>
  )
}
