import Head from 'next/head'
import Header from '../components/Header'


function Search() {
    return (
        <div>
            <Head>
                <title>Search Results</title>
                <meta name="description" content="Generated by create next app. Search It, a Google Clone." />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
        </div>
    )
}

export default Search;
